## README

This is an example tutorial on how to use pre-trained models to predict occupation codes for online advertisements.

Note that the software allows you to use these models to fine tune them for your training and test data.

**Models**: https://repod.icm.edu.pl/dataset.xhtml?persistentId=doi:10.18150/OCUTSI

**Publication**: Beręsewicz, M., Wydmuch, M., Cherniaiev, H., & Pater, R. (2024). Multilingual hierarchical classification of job advertisements for job vacancy statistics. arXiv preprint arXiv:2411.03779.

How to cite:
```tex
@misc{beręsewicz2024multilingualhierarchicalclassificationjob,
      title={Multilingual hierarchical classification of job advertisements for job vacancy statistics},
      author={Maciej Beręsewicz and Marek Wydmuch and Herman Cherniaiev and Robert Pater},
      year={2024},
      eprint={2411.03779},
      archivePrefix={arXiv},
      primaryClass={stat.AP},
      url={https://arxiv.org/abs/2411.03779},
}

@data{OCUTSI_2024,
      author = {Beręsewicz, Maciej and Wydmuch, Marek and Pater, Robert and Cherniaiev, Herman},
      publisher = {RepOD},
      title = "{Job offers classifiers for ISCO and KZiS 2023}",
      year = {2024},
      version = {V1},
      doi = {10.18150/OCUTSI},
      url = {https://doi.org/10.18150/OCUTSI}
}

```

## Setup (installation and models)

Note that we check the code for the Python versions: 3.9, 3.10 and 3.11.

In [ ]:
!python --version

Python 3.12.13

In [ ]:
!rm -rf job_offers_classifier

In [ ]:
!git clone https://github.com/OJALAB/job-ads-classifier.git
!mv job-ads-classifier/* ./
!rm -rf job-ads-classifier

Cloning into 'job-ads-classifier'...
remote: Enumerating objects: 230, done.
remote: Counting objects: 100% (230/230), done.
remote: Compressing objects: 100% (152/152), done.
remote: Total 230 (delta 112), reused 183 (delta 69), pack-reused 0 (from 0)
Receiving objects: 100% (230/230), 2.21 MiB | 29.41 MiB/s, done.
Resolving deltas: 100% (112/112), done.

In [ ]:
!pip install virtualenv
!virtualenv classifier
!classifier/bin/pip install --upgrade pip
!classifier/bin/pip install torch
!classifier/bin/pip install -r requirements-colab.txt

Collecting virtualenv
  Downloading virtualenv-21.6.0-py3-none-any.whl.metadata (3.4 kB)
Collecting distlib<1,>=0.3.7 (from virtualenv)
  Downloading distlib-0.4.3-py2.py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: filelock<4,>=3.24.2 in /usr/local/lib/python3.12/dist-packages (from virtualenv) (3.29.4)
Requirement already satisfied: platformdirs<5,>=3.9.1 in /usr/local/lib/python3.12/dist-packages (from virtualenv) (4.10.0)
Collecting python-discovery>=1.4.2 (from virtualenv)
  Downloading python_discovery-1.4.4-py3-none-any.whl.metadata (5.6 kB)
Downloading virtualenv-21.6.0-py3-none-any.whl (5.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 142.8 MB/s eta 0:00:00
Downloading distlib-0.4.3-py2.py3-none-any.whl (470 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 470.6/470.6 kB 45.8 MB/s eta 0:00:00
Downloading python_discovery-1.4.4-py3-none-any.whl (34 kB)
Installing collected packages: distlib, python-discovery, virtualenv
Successfully installed distlib-0.4.3 python-discovery-1.4.4 virtualenv-21.6.0
created virtual environment CPython3.12.13.final.0-64-x86_64 in 452ms
  creator CPython3Posix(dest=/content/classifier, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/root/.cache/virtualenv)
    added seed packages: pip==26.1.2
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator,XonshActivator
Requirement already satisfied: pip in ./classifier/lib/python3.12/site-packages (26.1.2)
Collecting torch
  Downloading torch-2.13.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (38 kB)
Collecting filelock (from torch)
  Downloading filelock-3.29.7-py3-none-any.whl.metadata (2.0 kB)
Collecting typing-extensions>=4.10.0 (from torch)
  Downloading typing_extensions-4.16.0-py3-none-any.whl.metadata (3.3 kB)
Collecting setuptools>=77.0.3 (from torch)
  Downloading setuptools-83.0.0-py3-none-any.whl.metadata (6.6 kB)
Collecting sympy>=1.13.3 (from torch)
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx>=2.5.1 (from torch)
  Downloading networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Collecting jinja2 (from torch)
  Downloading jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting fsspec>=0.8.5 (from torch)
  Downloading fsspec-2026.6.0-py3-none-any.whl.metadata (10 kB)
Collecting cuda-toolkit==13.0.3 (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch)
  Downloading cuda_toolkit-13.0.3.0-py2.py3-none-any.whl.metadata (17 kB)
Collecting cuda-bindings<14,>=13.0.3 (from torch)
  Downloading cuda_bindings-13.3.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (2.5 kB)
Collecting nvidia-cudnn-cu13==9.20.0.48 (from torch)
  Downloading nvidia_cudnn_cu13-9.20.0.48-py3-none-manylinux_2_27_x86_64.whl.metadata (1.9 kB)
Collecting nvidia-cusparselt-cu13==0.8.1 (from torch)
  Downloading nvidia_cusparselt_cu13-0.8.1-py3-none-manylinux2014_x86_64.whl.metadata (12 kB)
Collecting nvidia-nccl-cu13==2.29.7 (from torch)
  Downloading nvidia_nccl_cu13-2.29.7-py3-none-manylinux_2_18_x86_64.whl.metadata (2.1 kB)
Collecting nvidia-nvshmem-cu13==3.4.5 (from torch)
  Downloading nvidia_nvshmem_cu13-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.1 kB)
Collecting triton==3.7.1 (from torch)
  Downloading triton-3.7.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cublas==13.1.1.3.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch)
  Downloading nvidia_cublas-13.1.1.3-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cuda-nvrtc==13.0.88.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch)
  Downloading nvidia_cuda_nvrtc-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-runtime==13.0.96.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch)
  Downloading nvidia_cuda_runtime-13.0.96-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufft==12.0.0.61.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch)
  Downloading nvidia_cufft-12.0.0.61-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvjitlink<14,>=13.0.88 (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch)
  Downloading nvidia_nvjitlink-13.3.33-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cufile==1.15.1.6.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch)
  Downloading nvidia_cufile-1.15.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-cupti==13.0.85.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch)
  Downloading nvidia_cuda_cupti-13.0.85-py3-none-manylinux_2_25_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-curand==10.4.0.35.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch)
  Downloading nvidia_curand-10.4.0.35-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cusolver==12.0.4.66.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch)
  Downloading nvidia_cusolver-12.0.4.66-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparse==12.6.3.3.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch)
  Downloading nvidia_cusparse-12.6.3.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx==13.0.85.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch)
  Downloading nvidia_nvtx-13.0.85-py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl.metadata (1.8 kB)
Collecting cuda-pathfinder>=1.4.2 (from cuda-bindings<14,>=13.0.3->torch)
  Downloading cuda_pathfinder-1.5.6-py3-none-any.whl.metadata (1.9 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch)
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch)
  Downloading markupsafe-3.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.7 kB)
Downloading torch-2.13.0-cp312-cp312-manylinux_2_28_x86_64.whl (526.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 526.6/526.6 MB 36.0 MB/s  0:00:13
Downloading cuda_toolkit-13.0.3.0-py2.py3-none-any.whl (2.5 kB)
Downloading nvidia_cudnn_cu13-9.20.0.48-py3-none-manylinux_2_27_x86_64.whl (366.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 366.2/366.2 MB 48.0 MB/s  0:00:05
Downloading nvidia_cusparselt_cu13-0.8.1-py3-none-manylinux2014_x86_64.whl (170.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.1/170.1 MB 70.0 MB/s  0:00:02
Downloading nvidia_nccl_cu13-2.29.7-py3-none-manylinux_2_18_x86_64.whl (206.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 206.0/206.0 MB 73.8 MB/s  0:00:02
Downloading nvidia_nvshmem_cu13-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (60.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 MB 69.7 MB/s  0:00:00
Downloading triton-3.7.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (197.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 197.7/197.7 MB 76.1 MB/s  0:00:02
Downloading cuda_bindings-13.3.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (6.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.7/6.7 MB 163.6 MB/s  0:00:00
Downloading nvidia_cublas-13.1.1.3-py3-none-manylinux_2_27_x86_64.whl (423.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 423.1/423.1 MB 53.6 MB/s  0:00:05
Downloading nvidia_cuda_cupti-13.0.85-py3-none-manylinux_2_25_x86_64.whl (10.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 121.5 MB/s  0:00:00
Downloading nvidia_cuda_nvrtc-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (90.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.2/90.2 MB 69.7 MB/s  0:00:01
Downloading nvidia_cuda_runtime-13.0.96-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 118.2 MB/s  0:00:00
Downloading nvidia_cufft-12.0.0.61-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (214.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.1/214.1 MB 55.0 MB/s  0:00:03
Downloading nvidia_cufile-1.15.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 73.2 MB/s  0:00:00
Downloading nvidia_curand-10.4.0.35-py3-none-manylinux_2_27_x86_64.whl (59.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.5/59.5 MB 70.2 MB/s  0:00:00
Downloading nvidia_cusolver-12.0.4.66-py3-none-manylinux_2_27_x86_64.whl (200.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.9/200.9 MB 76.2 MB/s  0:00:02
Downloading nvidia_cusparse-12.6.3.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (145.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.9/145.9 MB 69.4 MB/s  0:00:02
Downloading nvidia_nvjitlink-13.3.33-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (40.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.7/40.7 MB 74.3 MB/s  0:00:00
Downloading nvidia_nvtx-13.0.85-py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl (148 kB)
Downloading cuda_pathfinder-1.5.6-py3-none-any.whl (52 kB)
Downloading fsspec-2026.6.0-py3-none-any.whl (203 kB)
Downloading networkx-3.6.1-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 89.1 MB/s  0:00:00
Downloading setuptools-83.0.0-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 51.5 MB/s  0:00:00
Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 135.8 MB/s  0:00:00
Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 29.2 MB/s  0:00:00
Downloading typing_extensions-4.16.0-py3-none-any.whl (45 kB)
Downloading filelock-3.29.7-py3-none-any.whl (46 kB)
Downloading jinja2-3.1.6-py3-none-any.whl (134 kB)
Downloading markupsafe-3.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (22 kB)
Installing collected packages: nvidia-cusparselt-cu13, mpmath, cuda-toolkit, typing-extensions, triton, sympy, setuptools, nvidia-nvtx, nvidia-nvshmem-cu13, nvidia-nvjitlink, nvidia-nccl-cu13, nvidia-curand, nvidia-cufile, nvidia-cuda-runtime, nvidia-cuda-nvrtc, nvidia-cuda-cupti, networkx, MarkupSafe, fsspec, filelock, cuda-pathfinder, nvidia-cusparse, nvidia-cufft, nvidia-cublas, jinja2, cuda-bindings, nvidia-cusolver, nvidia-cudnn-cu13, torch
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 29/29 [torch]
Successfully installed MarkupSafe-3.0.3 cuda-bindings-13.3.1 cuda-pathfinder-1.5.6 cuda-toolkit-13.0.3.0 filelock-3.29.7 fsspec-2026.6.0 jinja2-3.1.6 mpmath-1.3.0 networkx-3.6.1 nvidia-cublas-13.1.1.3 nvidia-cuda-cupti-13.0.85 nvidia-cuda-nvrtc-13.0.88 nvidia-cuda-runtime-13.0.96 nvidia-cudnn-cu13-9.20.0.48 nvidia-cufft-12.0.0.61 nvidia-cufile-1.15.1.6 nvidia-curand-10.4.0.35 nvidia-cusolver-12.0.4.66 nvidia-cusparse-12.6.3.3 nvidia-cusparselt-cu13-0.8.1 nvidia-nccl-cu13-2.29.7 nvidia-nvjitlink-13.3.33 nvidia-nvshmem-cu13-3.4.5 nvidia-nvtx-13.0.85 setuptools-83.0.0 sympy-1.14.0 torch-2.13.0 triton-3.7.1 typing-extensions-4.16.0
Collecting click==8.3.1 (from -r /content/requirements-colab-0.3.0.txt (line 3))
  Downloading click-8.3.1-py3-none-any.whl.metadata (2.6 kB)
Collecting lightning==2.6.1 (from -r /content/requirements-colab-0.3.0.txt (line 4))
  Downloading lightning-2.6.1-py3-none-any.whl.metadata (44 kB)
Collecting napkinxc==0.7.2 (from -r /content/requirements-colab-0.3.0.txt (line 5))
  Downloading napkinxc-0.7.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (6.0 kB)
Collecting numpy==2.4.3 (from -r /content/requirements-colab-0.3.0.txt (line 6))
  Downloading numpy-2.4.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting pandas==3.0.2 (from -r /content/requirements-colab-0.3.0.txt (line 7))
  Downloading pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting pyreadr==0.5.4 (from -r /content/requirements-colab-0.3.0.txt (line 8))
  Downloading pyreadr-0.5.4-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (1.3 kB)
Collecting pystempel==2.0.0 (from -r /content/requirements-colab-0.3.0.txt (line 9))
  Downloading pystempel-2.0.0-py3-none-any.whl.metadata (8.5 kB)
Collecting pytest==8.4.2 (from -r /content/requirements-colab-0.3.0.txt (line 10))
  Downloading pytest-8.4.2-py3-none-any.whl.metadata (7.7 kB)
Collecting scikit-learn==1.8.0 (from -r /content/requirements-colab-0.3.0.txt (line 11))
  Downloading scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Collecting scipy==1.16.3 (from -r /content/requirements-colab-0.3.0.txt (line 12))
  Downloading scipy-1.16.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (62 kB)
Collecting stop-words==2025.11.4 (from -r /content/requirements-colab-0.3.0.txt (line 13))
  Downloading stop_words-2025.11.4-py3-none-any.whl.metadata (14 kB)
Collecting torchmetrics==1.9.0 (from -r /content/requirements-colab-0.3.0.txt (line 14))
  Downloading torchmetrics-1.9.0-py3-none-any.whl.metadata (23 kB)
Collecting tqdm==4.67.3 (from -r /content/requirements-colab-0.3.0.txt (line 15))
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Collecting transformers==5.4.0 (from -r /content/requirements-colab-0.3.0.txt (line 16))
  Downloading transformers-5.4.0-py3-none-any.whl.metadata (32 kB)
Collecting PyYAML<8.0,>5.4 (from lightning==2.6.1->-r /content/requirements-colab-0.3.0.txt (line 4))
  Downloading pyyaml-6.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.4 kB)
Requirement already satisfied: fsspec<2028.0,>=2022.5.0 in ./classifier/lib/python3.12/site-packages (from fsspec[http]<2028.0,>=2022.5.0->lightning==2.6.1->-r /content/requirements-colab-0.3.0.txt (line 4)) (2026.6.0)
Collecting lightning-utilities<2.0,>=0.10.0 (from lightning==2.6.1->-r /content/requirements-colab-0.3.0.txt (line 4))
  Downloading lightning_utilities-0.15.3-py3-none-any.whl.metadata (5.5 kB)
Collecting packaging<27.0,>=23.0 (from lightning==2.6.1->-r /content/requirements-colab-0.3.0.txt (line 4))
  Downloading packaging-26.2-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: torch<4.0,>=2.1.0 in ./classifier/lib/python3.12/site-packages (from lightning==2.6.1->-r /content/requirements-colab-0.3.0.txt (line 4)) (2.13.0)
Requirement already satisfied: typing-extensions<6.0,>4.5.0 in ./classifier/lib/python3.12/site-packages (from lightning==2.6.1->-r /content/requirements-colab-0.3.0.txt (line 4)) (4.16.0)
Collecting pytorch-lightning (from lightning==2.6.1->-r /content/requirements-colab-0.3.0.txt (line 4))
  Downloading pytorch_lightning-2.6.5-py3-none-any.whl.metadata (21 kB)
Collecting gdown (from napkinxc==0.7.2->-r /content/requirements-colab-0.3.0.txt (line 5))
  Downloading gdown-6.1.0-py3-none-any.whl.metadata (8.3 kB)
Collecting python-dateutil>=2.8.2 (from pandas==3.0.2->-r /content/requirements-colab-0.3.0.txt (line 7))
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting sortedcontainers<3.0.0,>=2.4.0 (from pystempel==2.0.0->-r /content/requirements-colab-0.3.0.txt (line 9))
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Collecting iniconfig>=1 (from pytest==8.4.2->-r /content/requirements-colab-0.3.0.txt (line 10))
  Downloading iniconfig-2.3.0-py3-none-any.whl.metadata (2.5 kB)
Collecting pluggy<2,>=1.5 (from pytest==8.4.2->-r /content/requirements-colab-0.3.0.txt (line 10))
  Downloading pluggy-1.6.0-py3-none-any.whl.metadata (4.8 kB)
Collecting pygments>=2.7.2 (from pytest==8.4.2->-r /content/requirements-colab-0.3.0.txt (line 10))
  Downloading pygments-2.20.0-py3-none-any.whl.metadata (2.5 kB)
Collecting joblib>=1.3.0 (from scikit-learn==1.8.0->-r /content/requirements-colab-0.3.0.txt (line 11))
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn==1.8.0->-r /content/requirements-colab-0.3.0.txt (line 11))
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting huggingface-hub<2.0,>=1.5.0 (from transformers==5.4.0->-r /content/requirements-colab-0.3.0.txt (line 16))
  Downloading huggingface_hub-1.23.0-py3-none-any.whl.metadata (14 kB)
Collecting regex>=2025.10.22 (from transformers==5.4.0->-r /content/requirements-colab-0.3.0.txt (line 16))
  Downloading regex-2026.6.28-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers==5.4.0->-r /content/requirements-colab-0.3.0.txt (line 16))
  Downloading tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Collecting typer (from transformers==5.4.0->-r /content/requirements-colab-0.3.0.txt (line 16))
  Downloading typer-0.26.8-py3-none-any.whl.metadata (15 kB)
Collecting safetensors>=0.4.3 (from transformers==5.4.0->-r /content/requirements-colab-0.3.0.txt (line 16))
  Downloading safetensors-0.8.0-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]<2028.0,>=2022.5.0->lightning==2.6.1->-r /content/requirements-colab-0.3.0.txt (line 4))
  Downloading aiohttp-3.14.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (8.3 kB)
INFO: pip is looking at multiple versions of huggingface-hub to determine which version is compatible with other requirements. This could take a while.
Collecting huggingface-hub<2.0,>=1.5.0 (from transformers==5.4.0->-r /content/requirements-colab-0.3.0.txt (line 16))
  Downloading huggingface_hub-1.22.0-py3-none-any.whl.metadata (14 kB)
  Downloading huggingface_hub-1.21.0-py3-none-any.whl.metadata (14 kB)
  Downloading huggingface_hub-1.20.1-py3-none-any.whl.metadata (14 kB)
  Downloading huggingface_hub-1.20.0-py3-none-any.whl.metadata (14 kB)
  Downloading huggingface_hub-1.19.0-py3-none-any.whl.metadata (14 kB)
  Downloading huggingface_hub-1.18.0-py3-none-any.whl.metadata (14 kB)
  Downloading huggingface_hub-1.17.0-py3-none-any.whl.metadata (14 kB)
INFO: pip is still looking at multiple versions of huggingface-hub to determine which version is compatible with other requirements. This could take a while.
  Downloading huggingface_hub-1.16.4-py3-none-any.whl.metadata (14 kB)
  Downloading huggingface_hub-1.16.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: filelock>=3.10.0 in ./classifier/lib/python3.12/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers==5.4.0->-r /content/requirements-colab-0.3.0.txt (line 16)) (3.29.7)

In [ ]:
import sys
sys.path.append("classifier/lib/python3.12/site-packages")

Download multilingual models (around 20 min for each file)

*   top-down (`https://repod.icm.edu.pl/api/access/datafile/50892`)
*   bottom-up (`https://repod.icm.edu.pl/api/access/datafile/50893`)

In [ ]:
!wget https://repod.icm.edu.pl/api/access/datafile/50892 -O top-down.zip

--2026-07-09 21:22:41--  https://repod.icm.edu.pl/api/access/datafile/50892
Resolving repod.icm.edu.pl (repod.icm.edu.pl)... 213.135.60.199
Connecting to repod.icm.edu.pl (repod.icm.edu.pl)|213.135.60.199|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2117465081 (2.0G) [application/zip]
Saving to: ‘top-down.zip’

top-down.zip        100%[===================>]   1.97G  18.0MB/s    in 99s

2026-07-09 21:24:22 (20.3 MB/s) - ‘top-down.zip’ saved [2117465081/2117465081]

In [ ]:
!wget https://repod.icm.edu.pl/api/access/datafile/50893  -O bottom-up.zip

--2026-07-09 21:24:22--  https://repod.icm.edu.pl/api/access/datafile/50893
Resolving repod.icm.edu.pl (repod.icm.edu.pl)... 213.135.60.199
Connecting to repod.icm.edu.pl (repod.icm.edu.pl)|213.135.60.199|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3049932246 (2.8G) [application/zip]
Saving to: ‘bottom-up.zip’

bottom-up.zip       100%[===================>]   2.84G  21.8MB/s    in 2m 21s

2026-07-09 21:26:44 (20.6 MB/s) - ‘bottom-up.zip’ saved [3049932246/3049932246]

In [ ]:
!unzip -l top-down.zip

Archive:  top-down.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2024-10-23 10:26   transformer-multi-top-2024-sample-20/
        0  2024-10-25 06:48   transformer-multi-top-2024-sample-20/ckpts/
3392393018  2024-10-24 02:17   transformer-multi-top-2024-sample-20/ckpts/epoch=4-val_loss=0.31984.ckpt
   319109  2024-10-23 06:26   transformer-multi-top-2024-sample-20/hierarchy.bin
       88  2024-10-23 06:26   transformer-multi-top-2024-sample-20/transformer_arch.bin
---------                     -------
3392712215                     5 files

In [ ]:
!unzip top-down.zip

Archive:  top-down.zip
   creating: transformer-multi-top-2024-sample-20/
   creating: transformer-multi-top-2024-sample-20/ckpts/
  inflating: transformer-multi-top-2024-sample-20/ckpts/epoch=4-val_loss=0.31984.ckpt
  inflating: transformer-multi-top-2024-sample-20/hierarchy.bin
  inflating: transformer-multi-top-2024-sample-20/transformer_arch.bin

In [ ]:
!unzip bottom-up.zip

Archive:  bottom-up.zip
   creating: transformer-multi-bottom-2024-sample-20/
  inflating: transformer-multi-bottom-2024-sample-20/hierarchy.bin
  inflating: transformer-multi-bottom-2024-sample-20/transformer_arch.bin
   creating: transformer-multi-bottom-2024-sample-20/ckpts/
  inflating: transformer-multi-bottom-2024-sample-20/ckpts/epoch=6-val_loss=1.59784.ckpt
  inflating: transformer-multi-bottom-2024-sample-20/config.json
  inflating: transformer-multi-bottom-2024-sample-20/model.safetensors

## Loading library and simple prediction

Libraries and functions

In [ ]:
import numpy as np
import pandas as pd
from job_offers_classifier.load_save import load_to_df, save_obj, load_obj ## here it is not needed actually
from job_offers_classifier.job_offers_utils import create_hierarchy, fix_class_str, remove_classes, filter_classes, remap_classes ## here it is not needed actually
from job_offers_classifier.job_offers_classfier import *

poprawki

In [ ]:
import torch

_original_torch_load = torch.load
def _patched_torch_load(*args, **kwargs):
    kwargs["weights_only"] = False
    return _original_torch_load(*args, **kwargs)
torch.load = _patched_torch_load

Read the models

In [ ]:
trans_bottom = TransformerJobOffersClassifier(modeling_mode="bottom-up")
trans_bottom.load("transformer-multi-bottom-2024-sample-20")

trans_top = TransformerJobOffersClassifier(modeling_mode="top-down")
trans_top.load("transformer-multi-top-2024-sample-20")

Initializing TransformerClassifier with model_name=FacebookAI/xlm-roberta-base,
  output_size=2911, labels_groups=False,
  learning_rate=1e-05, weight_decay=0.01, warmup_steps=50, train_batch_size=8, eval_batch_size=8, freeze_transformer=False
  loss=flat cross entropy, hidden_dropout=0.0, hierarchy_leaves=2911 ...

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/615 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.12G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] XLMRobertaModel LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                       | Status     |  |
--------------------------+------------+--+-
lm_head.layer_norm.weight | UNEXPECTED |  |
lm_head.layer_norm.bias   | UNEXPECTED |  |
lm_head.dense.weight      | UNEXPECTED |  |
lm_head.bias              | UNEXPECTED |  |
lm_head.dense.bias        | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Initializing TransformerClassifier with model_name=FacebookAI/xlm-roberta-base,
  output_size=3543, labels_groups=True,
  learning_rate=1e-05, weight_decay=0.01, warmup_steps=50, train_batch_size=8, eval_batch_size=8, freeze_transformer=False
  loss=hierarchical cross entropy, hidden_dropout=0.0, hierarchy_leaves=2911 ...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] XLMRobertaModel LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                       | Status     |  |
--------------------------+------------+--+-
lm_head.layer_norm.weight | UNEXPECTED |  |
lm_head.layer_norm.bias   | UNEXPECTED |  |
lm_head.dense.weight      | UNEXPECTED |  |
lm_head.bias              | UNEXPECTED |  |
lm_head.dense.bias        | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Example offers

In [ ]:
example_offer = [
    "Starszy Statystyk w Ośrodku Metodologii Badań Ludnościowych OSOBA NA TYM STANOWISKU: Bierze współudział w rozwoju metodologii estymacji wielkości populacji i jej charakterystyk na podstawie zintegrowanych danych Prowadzi podstawowe prace projektowo-programistyczne dotyczące estymacji i integracji danych Współpracuje z departamentami GUS, urzędami statystycznymi i komórkami organizacyjnymi Urzędu w zakresie estymacji wielkości populacji i ich charakterystyk na podstawie zintegrowanych danych Uczestniczy we współpracy międzynarodowej w dziedzinie estymacji wielkości populacji i ich charakterystyk na podstawie zintegrowanych danych Współpracuje przy przygotowywaniu danych niezbędnych do realizacji zleceń zewnętrznych związanych z udostępnianiem informacji Bierze udział w rozpoznawaniu rejestrów administracyjnych jako baz danych ludnościowych Wykształcenie: średnie Znajomość języka angielskiego na poziomie komunikatywnym Podstawowa znajomość metod statystycznych ze szczególnym uwzględnieniem metody reprezentacyjnej Podstawowa znajomość pakietów statystycznych R lub Julia (ewentualnie Python) Umiejętność argumentowania Rzetelność Organizacja pracy i orientacja na osiąganie celów Wykorzystywanie wiedzy i doskonalenie zawodowe Współpraca Komunikacja interpersonalna Wykształcenie: wyższe profilowane (matematyka, informatyka, ekonomia) Doświadczenie zawodowe co najmniej 1 rok w obszarze metodologii badań statystycznych Znajomość programu badań statystycznych statystyki publicznej Myślenie analityczne Kreatywność",
    "Specjalista w Ośrodku Metodologii Badań Ludnościowych Koordynuje prace związane z projektami realizowanymi w Ośrodku Metodologii Badań Ludnościowych Przygotowywuje dokumenty związane z realizacją projektów Współpracuje z departamentami GUS Wykształcenie: wyższe Znajomość języka angielskiego na poziomie komunikatywnym Umiejętność zarządzania projektami Umiejętność argumentowania Rzetelność Organizacja pracy i orientacja na osiąganie celów Wykorzystywanie wiedzy i doskonalenie zawodowe Współpraca Komunikacja pisemna Komunikacja interpersonalna Wykształcenie: wyższe profilowane (ekonomia lub zarządzanie) Doświadczenie zawodowe co najmniej 1 rok w obszarze metodologii badań statystycznych Znajomość języka angielskiego na poziomie bardzo dobrym Znajomość programu badań statystycznych statystyki publicznej Myślenie analityczne Kreatywność",
    "We are seeking a highly skilled AI Solutions Engineer to join our team. The ideal candidate will have extensive experience in machine learning (ML) and Generative AI, focusing on both the strategic and tactical development of AI solutions. You will architect and deploy advanced AI systems, particularly around Generative AI, leveraging your deep technical expertise to build innovative products, solve complex problems and guide AI-driven strategies for the business. Bachelor’s or Master’s degree in Computer Science, Machine Learning, or a related field (PhD preferred). 5+ years of experience in building and deploying machine learning models, with proven experience in Generative AI. Expertise in Python and ML frameworks, and deep learning architectures for generative models. Proven experience in cloud platforms such as AWS or Azure for AI solution deployment. Experience in developing products utilizing Generative AI models, such as image generation, natural language generation, or synthetic data generation. Strong understanding of ML algorithms (supervised, unsupervised, reinforcement learning) and Generative AI techniques. Experience in scaling generative models and deploying them in production environments. Excellent communication skills to articulate technical concepts to non-technical stakeholders. Experience in NLP, computer vision, and deploying large language models (LLMs) for content generation - is an advantage. Hands-on experience with fine-tuning LLMs - is an advantage. Experience with MLOps frameworks and version control of models - is nice to have. Knowledge of product design principles using AI and ability to drive cross-functional AI projects with a generative component - is an asset.",
    "Ми шукаємо висококваліфікованого та досвідченого старшого спеціаліста з обробки даних/інженера штучного інтелекту, який приєднається до нашої команди. Як старший спеціаліст із обробки даних/інженер зі штучного інтелекту, ви відповідатимете за розробку та впровадження передових рішень із використанням Python, машинного навчання, магістратури права та класичних методологій НЛП. Ви тісно співпрацюватимете з нашою командою експертів, щоб аналізувати дані, будувати моделі та створювати інноваційні рішення (Gen)AI. Співпрацюйте з міжфункціональними командами для виявлення, розуміння та вирішення бізнес-проблем. Проектуйте, розробляйте та впроваджуйте передові алгоритми машинного навчання, моделі та конвеєри на основі LLM. Аналізуйте великі набори даних, щоб отримати значущу інформацію та шаблони. Напишіть якісний робочий код на Python, використовуючи стандартні найкращі методи розробки програмного забезпечення (git, тестування тощо). Будьте в курсі останніх досягнень ШІ, GenAI та науки про дані. Співпрацюйте з розробниками програмного забезпечення для інтеграції моделей AI у виробничі системи. Надавати керівництво та наставництво молодшим науковцям та інженерам із обробки даних. Ступінь бакалавра з комп’ютерних наук, даних або суміжної галузі. Мінімум 5 років досвіду в галузі обробки даних та розробки ШІ. Добре володію мовами програмування, такими як Python. Глибоке знання алгоритмів і методів машинного навчання. Досвід роботи з LLM і RAG або фреймворками агентів (Langchain, LLamaIndex тощо). Володіння техніками та бібліотеками NLP (Natural Language Processing). Сильні аналітичні навички вирішення проблем. Відмінні здібності до спілкування та співпраці. Вміння працювати самостійно та в команді. Сильна увага до деталей і вміння розставляти пріоритети завдань"
]

Prediction of the 1-digit occupation code

In [ ]:
pred_result_bottom = trans_bottom.predict(
    example_offer, # text data for which to make a prediction
    output_level=0, # the layer of the hierarchy for which to make a prediction (add a number from 0 - the first level, or ‘last’ if predicting for the last)
    top_k=None, # how many classes with the highest probability to predict, if None is returned the probability for all classes on the selected level of the hierarchy
    format='dataframe' # defines the format in which the result will be returned, possible options are ‘array’ - numpy.ndarray or ‘dataframe’ - pandas.DataFrame
)

INFO: Using 16bit Automatic Mixed Precision (AMP)
INFO:lightning.pytorch.utilities.rank_zero:Using 16bit Automatic Mixed Precision (AMP)
INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

Initializing TransformerDataModule with model_name=FacebookAI/xlm-roberta-base, max_seq_length=512, train/eval/predict_batch_size=8/8/8, num_workers(train/eval/predict)=2/2/2 ...
Starting predicting with TransformerClassifier ...
Setting up TransformerDataModule ...

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.10M [00:00<?, ?B/s]

INFO: Restoring states from the checkpoint path at transformer-multi-bottom-2024-sample-20/ckpts/epoch=6-val_loss=1.59784.ckpt
INFO:lightning.pytorch.utilities.rank_zero:Restoring states from the checkpoint path at transformer-multi-bottom-2024-sample-20/ckpts/epoch=6-val_loss=1.59784.ckpt
INFO: Lightning automatically upgraded your loaded checkpoint from v1.9.5 to v2.6.1. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint transformer-multi-bottom-2024-sample-20/ckpts/epoch=6-val_loss=1.59784.ckpt`
INFO:lightning.pytorch.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.9.5 to v2.6.1. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint transformer-multi-bottom-2024-sample-20/ckpts/epoch=6-val_loss=1.59784.ckpt`
/content/classifier/lib/python3.12/site-packages/lightning/pytorch/trainer/call.py:283: Be aware that when using `ckpt_path`, callbacks used to create the checkpoint need to be provided during `Trainer` instantiation. Please add the following callbacks: ["ModelCheckpoint{'monitor': 'val_loss', 'mode': 'min', 'every_n_train_steps': 0, 'every_n_epochs': 1, 'train_time_interval': None}"].
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO: Loaded model weights from the checkpoint at transformer-multi-bottom-2024-sample-20/ckpts/epoch=6-val_loss=1.59784.ckpt
INFO:lightning.pytorch.utilities.rank_zero:Loaded model weights from the checkpoint at transformer-multi-bottom-2024-sample-20/ckpts/epoch=6-val_loss=1.59784.ckpt
/content/classifier/lib/python3.12/site-packages/lightning/pytorch/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

Output()

In [ ]:
pred_result_top = trans_top.predict(
    example_offer,
    output_level=0,
    top_k=None,
    format="dataframe"
)

INFO: Using 16bit Automatic Mixed Precision (AMP)
INFO:lightning.pytorch.utilities.rank_zero:Using 16bit Automatic Mixed Precision (AMP)
INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

Initializing TransformerDataModule with model_name=FacebookAI/xlm-roberta-base, max_seq_length=512, train/eval/predict_batch_size=8/8/8, num_workers(train/eval/predict)=2/2/2 ...
Starting predicting with TransformerClassifier ...
Setting up TransformerDataModule ...

INFO: Restoring states from the checkpoint path at transformer-multi-top-2024-sample-20/ckpts/epoch=4-val_loss=0.31984.ckpt
INFO:lightning.pytorch.utilities.rank_zero:Restoring states from the checkpoint path at transformer-multi-top-2024-sample-20/ckpts/epoch=4-val_loss=0.31984.ckpt
INFO: Lightning automatically upgraded your loaded checkpoint from v1.9.5 to v2.6.1. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint transformer-multi-top-2024-sample-20/ckpts/epoch=4-val_loss=0.31984.ckpt`
INFO:lightning.pytorch.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.9.5 to v2.6.1. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint transformer-multi-top-2024-sample-20/ckpts/epoch=4-val_loss=0.31984.ckpt`
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO: Loaded model weights from the checkpoint at transformer-multi-top-2024-sample-20/ckpts/epoch=4-val_loss=0.31984.ckpt
INFO:lightning.pytorch.utilities.rank_zero:Loaded model weights from the checkpoint at transformer-multi-top-2024-sample-20/ckpts/epoch=4-val_loss=0.31984.ckpt

Output()

Predictions for each 1-digit occupation code for both models (2 two rows: bottop-up model, next two: top-down model).

In [ ]:
pd.concat([pred_result_bottom,pred_result_top])

,0,1,2,3,4,5,6,7,8,9
0,0.000042,0.006031,0.405446,0.237047,0.312859,0.007055,0.001011,0.018126,0.009057,0.003326
1,0.000012,0.063772,0.609497,0.038662,0.260210,0.008943,0.000518,0.010565,0.005032,0.002788
2,0.000014,0.004622,0.960128,0.011960,0.003015,0.003042,0.000914,0.008861,0.005032,0.002412
3,0.000012,0.002445,0.970233,0.012547,0.005936,0.001242,0.000463,0.003562,0.002545,0.001016
0,0.000312,0.002085,0.828093,0.052168,0.114952,0.000512,0.000613,0.000447,0.000461,0.000356
1,0.000270,0.123987,0.634598,0.002436,0.236208,0.001436,0.000466,0.000127,0.000087,0.000384
2,0.000955,0.010525,0.983270,0.000169,0.000623,0.001224,0.001909,0.000178,0.000515,0.000631
3,0.000597,0.001579,0.992638,0.000638,0.003393,0.000294,0.000584,0.000009,0.000091,0.000178

Prediction of 6-digits occupation code (top 3)

In [ ]:
pred_top3_bottom = trans_bottom.predict(
    example_offer,
    output_level="last",
    top_k=3,
    format="dataframe"
)

pred_top3_top = trans_top.predict(
    example_offer,
    output_level="last",
    top_k=3,
    format="dataframe"
)

INFO: Using 16bit Automatic Mixed Precision (AMP)
INFO:lightning.pytorch.utilities.rank_zero:Using 16bit Automatic Mixed Precision (AMP)
INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

Initializing TransformerDataModule with model_name=FacebookAI/xlm-roberta-base, max_seq_length=512, train/eval/predict_batch_size=8/8/8, num_workers(train/eval/predict)=2/2/2 ...
Starting predicting with TransformerClassifier ...
Setting up TransformerDataModule ...

INFO: Restoring states from the checkpoint path at transformer-multi-bottom-2024-sample-20/ckpts/epoch=6-val_loss=1.59784.ckpt
INFO:lightning.pytorch.utilities.rank_zero:Restoring states from the checkpoint path at transformer-multi-bottom-2024-sample-20/ckpts/epoch=6-val_loss=1.59784.ckpt
INFO: Lightning automatically upgraded your loaded checkpoint from v1.9.5 to v2.6.1. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint transformer-multi-bottom-2024-sample-20/ckpts/epoch=6-val_loss=1.59784.ckpt`
INFO:lightning.pytorch.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.9.5 to v2.6.1. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint transformer-multi-bottom-2024-sample-20/ckpts/epoch=6-val_loss=1.59784.ckpt`
/content/classifier/lib/python3.12/site-packages/lightning/pytorch/trainer/call.py:283: Be aware that when using `ckpt_path`, callbacks used to create the checkpoint need to be provided during `Trainer` instantiation. Please add the following callbacks: ["ModelCheckpoint{'monitor': 'val_loss', 'mode': 'min', 'every_n_train_steps': 0, 'every_n_epochs': 1, 'train_time_interval': None}"].
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO: Loaded model weights from the checkpoint at transformer-multi-bottom-2024-sample-20/ckpts/epoch=6-val_loss=1.59784.ckpt
INFO:lightning.pytorch.utilities.rank_zero:Loaded model weights from the checkpoint at transformer-multi-bottom-2024-sample-20/ckpts/epoch=6-val_loss=1.59784.ckpt
/content/classifier/lib/python3.12/site-packages/lightning/pytorch/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

Output()

INFO: Using 16bit Automatic Mixed Precision (AMP)
INFO:lightning.pytorch.utilities.rank_zero:Using 16bit Automatic Mixed Precision (AMP)
INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

Initializing TransformerDataModule with model_name=FacebookAI/xlm-roberta-base, max_seq_length=512, train/eval/predict_batch_size=8/8/8, num_workers(train/eval/predict)=2/2/2 ...
Starting predicting with TransformerClassifier ...
Setting up TransformerDataModule ...

INFO: Restoring states from the checkpoint path at transformer-multi-top-2024-sample-20/ckpts/epoch=4-val_loss=0.31984.ckpt
INFO:lightning.pytorch.utilities.rank_zero:Restoring states from the checkpoint path at transformer-multi-top-2024-sample-20/ckpts/epoch=4-val_loss=0.31984.ckpt
INFO: Lightning automatically upgraded your loaded checkpoint from v1.9.5 to v2.6.1. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint transformer-multi-top-2024-sample-20/ckpts/epoch=4-val_loss=0.31984.ckpt`
INFO:lightning.pytorch.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.9.5 to v2.6.1. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint transformer-multi-top-2024-sample-20/ckpts/epoch=4-val_loss=0.31984.ckpt`
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO: Loaded model weights from the checkpoint at transformer-multi-top-2024-sample-20/ckpts/epoch=4-val_loss=0.31984.ckpt
INFO:lightning.pytorch.utilities.rank_zero:Loaded model weights from the checkpoint at transformer-multi-top-2024-sample-20/ckpts/epoch=4-val_loss=0.31984.ckpt

Output()

Results for top 3 along with the probabilities

In [ ]:
pd.concat([pred_top3_bottom,pred_top3_top])

  class_1 class_2 class_3    prob_1    prob_2    prob_3
0  431201  331401  252102  0.287995  0.193351  0.171970
1  242290  441990  411090  0.114436  0.080515  0.079889
2  251908  252102  251201  0.767520  0.035479  0.032053
3  251908  252102  252990  0.574627  0.329980  0.011291
0  212004  216590  431201  0.404573  0.082240  0.058331
1  242112  411090  242102  0.274786  0.129537  0.077129
2  251908  251201  251202  0.387136  0.223938  0.161336
3  252102  251908  252990  0.493148  0.336075  0.033628